# Generated by Django 5.2.1 on 2025-05-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('doc_type', models.CharField(choices=[('django', 'Django'), ('javascript', 'JavaScript'), ('python', 'Python'), ('git', 'Git'), ('postman', 'Postman'), ('vscode', 'VS Code'), ('docker', 'Docker'), ('npm', 'NPM'), ('aws', 'AWS CLI'), ('github', 'GitHub'), ('other', 'Other')], max_length=20)),
                ('documentation_file', models.FileField(upload_to='documentation_files/')),
                ('ai_documentation_file', models.FileField(blank=True, null=True, upload_to='ai_documentation_files/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
