# Generated by Django 5.2.1 on 2025-05-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentationfile',
            name='ai_documentation_file',
            field=models.FileField(blank=True, null=True, upload_to='ai_documentation/'),
        ),
        migrations.AlterField(
            model_name='documentationfile',
            name='documentation_file',
            field=models.FileField(blank=True, null=True, upload_to='documentation/'),
        ),
    ]
