# Generated by Django 5.2.1 on 2025-06-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_documentationfile_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentationfile',
            name='doc_type',
            field=models.CharField(choices=[('django', 'Django'), ('javascript', 'JavaScript'), ('python', 'Python'), ('git', 'Git'), ('postman', 'Postman'), ('vscode', 'VS Code'), ('docker', 'Docker'), ('awscli', 'AWS CLI'), ('github', 'GitHub'), ('react', 'React'), ('kubernetes', 'Kubernetes'), ('Pytest', 'Pytest'), ('fastapi', 'Fast API'), ('java', 'Java'), ('gitlab', 'GitLab'), ('c', 'C'), ('c++', 'C++'), ('flask', 'Flask'), ('vuejs', 'Vue.js'), ('tensorflow', 'TensorFlow'), ('kotlin', 'Kotlin'), ('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('linux', 'Linux'), ('other', 'Other')], max_length=20),
        ),
    ]
